FROM node:20-alpine AS base
RUN apk add --no-cache tzdata
ENV TZ=Europe/Warsaw
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci || npm install
COPY . .

FROM base AS dev
EXPOSE 5173 24678
CMD ["npm","run","dev","--","--host","0.0.0.0","--port","5173"]

FROM base AS build
RUN npm run build

FROM nginx:stable-alpine AS prod
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
