services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
      target: base
    environment:
      DB_DIR: /app/data
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - "3010:3001"
    volumes:
      - sqlite-data-prod:/app/data
    restart: unless-stopped
    command: ["node", "server.js"]

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
      target: prod
    ports:
      - "3005:80"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped

volumes:
  sqlite-data-prod:
    name: biuro_sqlite-data-prod
